---
title: "Return-impact"
author: "Peimin Lin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo =TRUE, 
  message = FALSE,
  warning = FALSE,
  cache = TRUE,
  fig.align = "center")
library(tidyverse) 
library(pacman)
library(rio)
library(skimr)
library(broom) 
library(magrittr)
library(ROCR)
library(MASS)
library(caTools)
library(DMwR)
library(caret)
library(ggplot2)
library(patchwork)
library(vcd)
library(gridExtra)
library(knitr)
library(corrplot)
library(scales)
library(lme4)
library(DMwR)
library(InformationValue)
library(ROCR)
library(rpart)
library(randomForest)
library(xgboost)
library(xgboostExplainer)
library(ggmosaic)
library(e1071)
library(ranger)
library(penalized)
library(rpart.plot)
library(ggcorrplot)
library(caTools)
library(doMC)
library(partykit)
library(rattle)
library(jpeg)
library(png)
library(ggExtra)
library(cluster)
library(NbClust)
library(flexclust)
library(fMultivar)
library(rattle)
library(Rmixmod)
library(mclust)
registerDoMC(cores=4)
```


```{r read_data}
positions <- readRDS("/monash-return-impact/data/position.rds")  
```


```{r}
summarydata <- summary(positions)

summarydata
```


```{r}
serveone <- positions %>% 
  dplyr::filter(serve == 1)
```


```{r}
servetwo <- positions %>% 
  dplyr::filter(serve == 2)
```



# Marginal Distribution

```{r}
ggMarginal()
```
 

# GMM Rmixmod


# 3 clusters

```{r}
modelo3 <- mixmodCluster(serveone[,c("X","Y")], 3)
modelo3
```


```{r}
plot(modelo3)
```

```{r}
models3 <- mixmodCluster(servetwo[,c("X","Y")], 3)
models3
```


```{r}
plot(models3)
```

# cluster 4

```{r}
modelo4 <- mixmodCluster(serveone[,c("X","Y")], 4)
modelo4
plot(modelo4)
```


```{r}
models4 <- mixmodCluster(servetwo[,c("X","Y")], 4)
models4
plot(models4)
```

# Cluster 5

```{r}
modelo5 <- mixmodCluster(serveone[,c("X","Y")], 5)
modelo5
plot(modelo5)
```


```{r}
models5 <- mixmodCluster(servetwo[,c("X","Y")], 5)
models5
plot(models5)
```


# Cluster 6


```{r}
modelo6 <- mixmodCluster(serveone[,c("X","Y")], 6)
modelo6
plot(modelo6)
```


```{r}
models6 <- mixmodCluster(servetwo[,c("X","Y")], 6)
models6
plot(models6)
```

# Cluster 7 


```{r}
modelo7 <- mixmodCluster(serveone[,c("X","Y")], 7)
modelo7
plot(modelo7)
```

```{r}
models7 <- mixmodCluster(servetwo[,c("X","Y")], 7)
models7
plot(models7)
```


# Cluster 8 

```{r}
modelo8 <- mixmodCluster(serveone[,c("X","Y")], 8)
modelo8
plot(modelo8)
```


```{r}
models8 <- mixmodCluster(servetwo[,c("X","Y")], 8)
models8
plot(models8)
```



# Cluster 9 


```{r}
modelo9 <- mixmodCluster(serveone[,c("X","Y")], 9)
modelo9
plot(modelo9)
```



```{r}
models9 <- mixmodCluster(servetwo[,c("X","Y")], 9)
models9
plot(models9)
```

# Cluster 10

```{r}
modelo10 <- mixmodCluster(serveone[,c("X","Y")], 10)
modelo10
plot(modelo10)
```

```{r}
models10 <- mixmodCluster(servetwo[,c("X","Y")], 10)
models10
plot(models10)
```


# Cluster 11 

```{r}
modelo11 <- mixmodCluster(serveone[,c("X","Y")], 11)
modelo11
plot(modelo11)
```


```{r}
models11 <- mixmodCluster(servetwo[,c("X","Y")], 11)
models11
plot(models11)
```


# Cluster 12 

```{r}
modelo12 <- mixmodCluster(serveone[,c("X","Y")], 12)
modelo12
plot(modelo12)
```



```{r}
models12 <- mixmodCluster(servetwo[,c("X","Y")], 12)
models12
plot(models12)
```


```{r}
summary(modelo3)
summary(modelo4)
summary(modelo5)
summary(modelo6)
summary(modelo7)
summary(modelo8)
```

# Player 

```{r}
playerone <- serveone %>%
  dplyr::filter(player %in% c("N. Djokovic", "R. Federer", "D. Thiem", "A. Zverev", "D. Schwartzman", "R. Nadal", "D. Medvedev", "S. Tsitsipas", "A. Rublev", "M. Berrettini", "R. Bautista Agut", "P. Carreno Busta") |
opponent %in% c("N. Djokovic", "R. Federer", "D. Thiem", "A. Zverev", "D. Schwartzman", "R. Nadal", "D. Medvedev", "S. Tsitsipas", "A. Rublev", "M. Berrettini", "R. Bautista Agut", "P. Carreno Busta") 
                  )
```


```{r}
pmodo3 <- mixmodCluster(playerone[,c("X","Y")], 3)
plot(pmodo3 )
```






















